language: node_js

node_js:
  - "10"

cache:
  yarn: true
  directories:
    - "node_modules"
branches:
  only:
  - master

install:
  - yarn install
  - yarn generate

script:
  - echo "Skipping tests"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  target-branch: gh-pages
  keep-history: true
  local-dir: dist
  on:
    branch: master
